services:
  - name: cloud-app
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    repo: https://github.com/Kouyate01/render_yaml.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: frankfurt
    plan: free